pcm.astraout {
    type plug
    slave.pcm {
        type softvol
        slave.pcm {
            type plug
            slave {
                pcm "hw:CARD=dolphinasoc,DEV=0"
                rate 48000
                channels 2
                format S16_LE
            }
        }
        control.name "AstraVolume"
        control.card dolphinasoc
    }
}
